# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(max_length=200)),
                ('smtp_port', models.CharField(max_length=5)),
                ('email_sender', models.CharField(max_length=200)),
                ('password_email_sender', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Global Parameter',
                'verbose_name_plural': 'Global Parameters',
            },
        ),
    ]
