# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuousdelivery', '0002_serverjboss'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverjboss',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
